### ISSUE TITLE
Purity wand focus deletes Block of Flesh

### ISSUE THREAD

**Issue by DiamondIceNS** [Midnight145/blightbuster#7]
The Block of Flesh from Thaumcraft shares its block ID with Crusted Taint and Tainted Soil. The Purity wand focus removes blocks on right-click based on block ID only, so the Block of Flesh is erroneously treated as a tainted block and removed.

This has been found via source code review and confirmed via live test.

This bug is extremely specific and I bet it inconvenienced _literally no one ever_, but the fix should be extremely simple.

Thank you for your time.

**Comment by Midnight145** [comment]
fixed, added metadata check, will be available in the next build
